version: "3.8"

services:
  app:
    build: .
    environment:
      - POSTGRES_URL=jdbc:postgresql://db:5432/selling-app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - SPRING_DLL_AUTO=create
      - SPRING_SQL_FORMAT_SQL=true
      - SPRING_SHOW_SQL=true
      - SERVER_PORT=8443
    depends_on:
      - db
    ports:
      - "8443:8443"
  db:
    image: postgres:14
    environment:
      - POSTGRES_DB=selling-app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    ports:
      - "5432:5432"
